component_depth: 7
default_excludes: true
languages:
  - name: java
    production:
      exclude:
        - .*/restControllers/.*\.java
        - .*/lightWeight/.*\.java
    test:
      include:
        - .*/test/.*\.java

