component_depth: 7
default_excludes: true
languages:
  - name: java
    production:
      exclude:
        - .*/restControllers/.*\.java
        - .*/lightWeight/.*\.java
        - .*/parser/.*\.java
        - .*/util/.*\.java
        - .*/parsedComponent/.*\.java
    test:
      include:
        - .*/test/.*\.java

